<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_What type is it_filetype</name>
   <tag></tag>
   <elementGuidId>e76d810c-9c97-41f6-bd56-564ab7c6f305</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#itsanimage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='itsanimage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>198e3674-cfbc-4e8b-81b2-2420cc4682c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>65e7e838-f4d5-4156-8f93-c4ff0f701864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>itsanimage</value>
      <webElementGuid>78cfa83f-27d9-40e8-abdd-7058303917da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>filetype</value>
      <webElementGuid>a53703c0-1f16-465b-abe7-d2e424974d50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>1852f7ab-2bfb-489a-a6dc-be35680e59a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;itsanimage&quot;)</value>
      <webElementGuid>087e3206-8272-4fdb-be22-299427f25c46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='itsanimage']</value>
      <webElementGuid>a260de7b-0ae8-4ee0-9c19-6b09ca0f0f9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>99e2559f-e535-4286-af33-8711264b2948</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'itsanimage' and @name = 'filetype']</value>
      <webElementGuid>4cd4a8af-5485-44e5-9532-b14fcad05aba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
